services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus-registry
    restart: unless-stopped
    ports:
      - "8081:8081"   # Nexus web UI
      - "8082:8082"   # Docker registry port
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx1g -XX:MaxDirectMemorySize=2g
    volumes:
      - nexus-data:/nexus-data
    networks:
      - nexus-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  nexus-data:
    driver: local

networks:
  nexus-net:
    driver: bridge